CREATE TABLE admin_order_controls (
  order_id VARCHAR(40) PRIMARY KEY,
  risk VARCHAR(32) NOT NULL DEFAULT 'LOW',
  entitlement VARCHAR(32) NOT NULL DEFAULT 'PENDING',
  note VARCHAR(512) NOT NULL DEFAULT '',
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
