CREATE TABLE app_users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  device_id VARCHAR(128) NOT NULL UNIQUE,
  nickname VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE dramas (
  id BIGINT PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  tag VARCHAR(64) NOT NULL,
  episode_count INT NOT NULL DEFAULT 0,
  heat_text VARCHAR(32) NOT NULL DEFAULT '0',
  cover_url VARCHAR(512) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
  play_count BIGINT NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE story_pools (
  id VARCHAR(64) PRIMARY KEY,
  drama_id BIGINT NOT NULL,
  name VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  draw_price DECIMAL(10, 2) NOT NULL DEFAULT 6.00,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_story_pools_drama FOREIGN KEY (drama_id) REFERENCES dramas(id)
);

CREATE TABLE storylines (
  id VARCHAR(64) PRIMARY KEY,
  drama_id BIGINT NOT NULL,
  pool_id VARCHAR(64) NOT NULL,
  name VARCHAR(128) NOT NULL,
  rarity VARCHAR(16) NOT NULL DEFAULT 'R',
  description VARCHAR(512) NOT NULL,
  cover_url VARCHAR(512) NOT NULL,
  weight DECIMAL(8, 3) NOT NULL DEFAULT 1.000,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  sort_order INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_storylines_drama FOREIGN KEY (drama_id) REFERENCES dramas(id),
  CONSTRAINT fk_storylines_pool FOREIGN KEY (pool_id) REFERENCES story_pools(id)
);

CREATE TABLE episodes (
  id VARCHAR(64) PRIMARY KEY,
  drama_id BIGINT NOT NULL,
  episode_no INT NOT NULL,
  title VARCHAR(128) NOT NULL,
  storyline_id VARCHAR(64) NULL,
  cover_url VARCHAR(512) NOT NULL,
  video_url VARCHAR(512) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
  pay_node BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_episodes_drama FOREIGN KEY (drama_id) REFERENCES dramas(id),
  CONSTRAINT fk_episodes_storyline FOREIGN KEY (storyline_id) REFERENCES storylines(id)
);

CREATE TABLE orders (
  id VARCHAR(40) PRIMARY KEY,
  user_id BIGINT NOT NULL,
  drama_id BIGINT NOT NULL,
  storyline_id VARCHAR(64) NULL,
  title VARCHAR(128) NOT NULL,
  amount DECIMAL(10, 2) NOT NULL,
  payment_method VARCHAR(64) NOT NULL,
  payment_method_key VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL,
  paid_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_orders_user FOREIGN KEY (user_id) REFERENCES app_users(id),
  CONSTRAINT fk_orders_drama FOREIGN KEY (drama_id) REFERENCES dramas(id),
  CONSTRAINT fk_orders_storyline FOREIGN KEY (storyline_id) REFERENCES storylines(id)
);

CREATE TABLE user_unlocks (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  user_id BIGINT NOT NULL,
  drama_id BIGINT NOT NULL,
  storyline_id VARCHAR(64) NOT NULL,
  order_id VARCHAR(40) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uk_user_storyline (user_id, storyline_id),
  CONSTRAINT fk_unlocks_user FOREIGN KEY (user_id) REFERENCES app_users(id),
  CONSTRAINT fk_unlocks_drama FOREIGN KEY (drama_id) REFERENCES dramas(id),
  CONSTRAINT fk_unlocks_storyline FOREIGN KEY (storyline_id) REFERENCES storylines(id),
  CONSTRAINT fk_unlocks_order FOREIGN KEY (order_id) REFERENCES orders(id)
);

CREATE TABLE admin_snapshots (
  id VARCHAR(64) PRIMARY KEY,
  payload JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
