ALTER TABLE app_users
  ADD COLUMN email VARCHAR(128) NOT NULL DEFAULT '',
  ADD COLUMN admin_note VARCHAR(255) NOT NULL DEFAULT '';

CREATE TABLE admin_users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_salt VARCHAR(64) NOT NULL,
  password_hash VARCHAR(128) NOT NULL,
  display_name VARCHAR(64) NOT NULL,
  role_key VARCHAR(64) NOT NULL DEFAULT 'administrator',
  permissions JSON NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'ENABLED',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE admin_auth_tokens (
  token VARCHAR(128) PRIMARY KEY,
  admin_id BIGINT NOT NULL,
  expires_at TIMESTAMP NOT NULL,
  revoked BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_admin_tokens_user FOREIGN KEY (admin_id) REFERENCES admin_users(id)
);
